baseURL: https://satooru.me

languageCode: en-us
title: "SatooRu's Profile"
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

# Control TOC depth
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
  goldmark:
    renderer:
      unsafe: true

logo:
  main: images/satooru.png
  inverted: images/satooru.png
  favicon: images/satooru.png

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  background: "images/background.png"
  # GitHub repo URL of your site
  gitRepo: https://github.com/SatooRu65536/profile

  # specify whether you want to write some blog posts or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false

  darkMode:
    enable: false
